name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:

  test-code:
    name: Test python code with local libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m venv venv
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install pyserial==3.5
      - name: Run tests
        run: |
          source ./venv/bin/activate
          dir -ls
          python3 ./tests/fake.py

  build-wheel:
    name: Build Python package and test it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies and build package
        run: |
          python -m venv venv
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade pyserial==3.5 build
          python -m build
          pip install ./dist/iu2frl_civ-0.0.0.tar.gz
          python3 ./tests/fake.py

  pypi-publish:
    needs: [test-code, build-wheel]
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/iu2frl-civ
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies and build package
        run: |
          python -m venv venv
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install pyserial==3.5 setuptools wheel build
          sed -i 's/version = "v0.0.0"/version = "${{ steps.get-latest-tag.outputs.tag }}"/' ./pyproject.toml
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1