name: Validate Python Package and test code

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  call-test-code:
    name: Call Test Python Code with Local Libraries and Build Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check local files
        run: |
          ls -a
      - name: Call Test Code
        uses: ./.github/workflows/validate/