name: Validate Python Package and test code

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  call-validate-local:
    name: Call Test Python Code with Local Libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check local files
        run: |
          ls -a
      - name: Call action to validate local code
        uses: ./.github/workflows/validate-local/
  
  call-validate-wheel:
    name: Call Test Python Code to Build Wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check local files
        run: |
          ls -a
      - name: Call action to validate wheel
        uses: ./.github/workflows/validate-wheel/